### PR TITLE
Add slow indexing parser

### PR DESCRIPTION
**Pull request by jdoss**
Elasticsearch slow indexing has a different log format than the slow query log. This PR adds in support for parsing the slow indexing log. Note that the fix from https://github.com/iaintshine/fluent-plugin-esslowquery/pull/1 is included in this PR as well.

### CODE REVIEW

**Comment by jdoss** [comment]
Hey @iaintshine any comments on my PR? It fixes some edge cases with the regex and adds in support for slow index logging.

**Comment by bmista** [comment]
Hey @jdoss, sorry for the delay, I didn't have time to test the PR. Will do this week. Also I guess we need to introduce specs into the repo, since it's getting harder and harder to introduce changes.

**Comment by bmista** [comment]
Hi @jdoss,

can you update the severity regexp so it's consistent with master and rebase the PR as it got stale ?

**Comment by jdoss** [comment]
@iaintshine OK rebased on master and updated severity regexp.

**Comment by bmista** [comment]
:ship:

**Comment by bmista** [comment]
Thanks @jdoss! I appreciate your work!

**Pull request merged**
